# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FitnessProjectOneWeek' do
    pod 'AFNetworking'
    pod 'SDWebImage'
    pod 'FBSDKCoreKit'
    pod 'FBSDKShareKit'
    pod 'FBSDKLoginKit'
    pod 'Realm'
end
