# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FitnessProjectOneWeek' do
    pod 'AFNetworking', '~> 3.0'
    pod 'SDWebImage', '~>3.8'
    pod 'FBSDKCoreKit'
    pod 'FBSDKShareKit'
    pod 'FBSDKLoginKit'
end
